-- Balanced friend data with 100+ entries
-- Balanced friend data with 100+ entries
INSERT INTO friends (sender_id, receiver_id, status) VALUES
                                                         (1, 2, 'ACCEPTED'),
                                                         (1, 3, 'ACCEPTED'),
                                                         (1, 4, 'ACCEPTED'),
                                                         (1, 5, 'ACCEPTED'),
                                                         (1, 6, 'ACCEPTED'),
                                                         (1, 7, 'ACCEPTED'),
                                                         (1, 8, 'ACCEPTED'),
                                                         (1, 9, 'ACCEPTED'),
                                                         (1, 10, 'ACCEPTED'),
                                                         (2, 3, 'ACCEPTED'),
                                                         (2, 4, 'ACCEPTED'),
                                                         (2, 5, 'ACCEPTED'),
                                                         (2, 6, 'ACCEPTED'),
                                                         (2, 7, 'ACCEPTED'),
                                                         (2, 8, 'ACCEPTED'),
                                                         (2, 9, 'ACCEPTED'),
                                                         (2, 10, 'ACCEPTED'),
                                                         (3, 4, 'ACCEPTED'),
                                                         (3, 5, 'ACCEPTED'),
                                                         (3, 6, 'ACCEPTED'),
                                                         (3, 7, 'ACCEPTED'),
                                                         (3, 8, 'ACCEPTED'),
                                                         (3, 9, 'ACCEPTED'),
                                                         (3, 10, 'ACCEPTED'),
                                                         (4, 5, 'ACCEPTED'),
                                                         (4, 6, 'ACCEPTED'),
                                                         (4, 7, 'ACCEPTED'),
                                                         (4, 8, 'ACCEPTED'),
                                                         (4, 9, 'ACCEPTED'),
                                                         (4, 10, 'ACCEPTED'),
                                                         (5, 6, 'ACCEPTED'),
                                                         (5, 7, 'ACCEPTED'),
                                                         (5, 8, 'ACCEPTED'),
                                                         (5, 9, 'ACCEPTED'),
                                                         (5, 10, 'ACCEPTED'),
                                                         (6, 7, 'PENDING'),
                                                         (6, 8, 'PENDING'),
                                                         (6, 9, 'PENDING'),
                                                         (6, 10, 'PENDING'),
                                                         (7, 8, 'PENDING'),
                                                         (7, 9, 'PENDING'),
                                                         (7, 10, 'PENDING'),
                                                         (8, 9, 'DECLINED'),
                                                         (8, 10, 'DECLINED'),
                                                         (9, 10, 'BLOCK');

-- 제약 조건 위배되는 중복된 관계는 삭제되었으며, 송신자와 수신자가 같은 경우도 처리
